-- MySQL Script generated by MySQL Workbench
-- 06/26/15 11:27:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nad_testjuin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nad_testjuin` ;

-- -----------------------------------------------------
-- Schema nad_testjuin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nad_testjuin` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema nad_testjuin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nad_testjuin` ;

-- -----------------------------------------------------
-- Schema nad_testjuin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nad_testjuin` DEFAULT CHARACTER SET utf8 ;
USE `nad_testjuin` ;

-- -----------------------------------------------------
-- Table `nad_testjuin`.`droit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`droit` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`droit` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `lenom` VARCHAR(45) NULL,
  `laperm` SMALLINT(80) UNSIGNED NULL DEFAULT 2,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`utilisateur` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `lelogin` VARCHAR(100) NULL,
  `lepass` VARCHAR(45) NULL,
  `lemail` VARCHAR(150) NULL,
  `lenom` VARCHAR(80) NULL,
  `valide` TINYINT(80) UNSIGNED NULL DEFAULT 1,
  `droit_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lelogin_UNIQUE` (`lelogin` ASC),
  INDEX `fk_utilisateur_droit_idx` (`droit_id` ASC),
  CONSTRAINT `fk_utilisateur_droit`
    FOREIGN KEY (`droit_id`)
    REFERENCES `nad_testjuin`.`droit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`photo` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lenom` VARCHAR(50) NULL,
  `lextension` CHAR(3) NULL,
  `lepoids` INT UNSIGNED NULL,
  `lalargeur` INT UNSIGNED NULL,
  `lahauteur` INT UNSIGNED NULL,
  `letitre` VARCHAR(60) NULL,
  `ladesc` VARCHAR(500) NULL,
  `affiche` SMALLINT(80) UNSIGNED NULL DEFAULT 2,
  `utilisateur_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lenom_UNIQUE` (`lenom` ASC),
  INDEX `fk_photo_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_photo_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `nad_testjuin`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`rubriques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`rubriques` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`rubriques` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lintitule` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`photo_has_rubriques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`photo_has_rubriques` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`photo_has_rubriques` (
  `photo_id` INT UNSIGNED NOT NULL,
  `rubriques_id` INT UNSIGNED NOT NULL,
  INDEX `fk_photo_has_rubriques_rubriques1_idx` (`rubriques_id` ASC),
  INDEX `fk_photo_has_rubriques_photo1_idx` (`photo_id` ASC),
  CONSTRAINT `fk_photo_has_rubriques_photo1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `nad_testjuin`.`photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo_has_rubriques_rubriques1`
    FOREIGN KEY (`rubriques_id`)
    REFERENCES `nad_testjuin`.`rubriques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `nad_testjuin` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
