-- MySQL Script generated by MySQL Workbench
-- 06/24/15 12:17:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nad_testjuin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nad_testjuin` ;

-- -----------------------------------------------------
-- Schema nad_testjuin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nad_testjuin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `nad_testjuin` ;

-- -----------------------------------------------------
-- Table `nad_testjuin`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`utilisateur` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `lelogin` VARCHAR(100) NULL,
  `lepass` VARCHAR(45) NULL,
  `lemail` VARCHAR(150) NULL,
  `lenom` VARCHAR(80) NULL,
  `valide` TINYINT(100) UNSIGNED NULL DEFAULT 1,
  `droit_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Lelogin_UNIQUE` (`lelogin` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`droit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`droit` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`droit` (
  `id` INT NULL AUTO_INCREMENT,
  `lenom` VARCHAR(45) NULL,
  `laperm` SMALLINT(100) UNSIGNED NULL DEFAULT 2,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lenom_UNIQUE` (`lenom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`photo` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`photo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lenom` VARCHAR(50) NULL,
  `lextension` CHAR(3) NULL,
  `lepoids` INT UNSIGNED NULL,
  `lalargeur` INT UNSIGNED NULL,
  `lahauteur` INT UNSIGNED NULL,
  `letitre` VARCHAR(60) NULL,
  `ladesc` VARCHAR(500) NULL,
  `affiche` SMALLINT(100) UNSIGNED NULL DEFAULT 2,
  `utilisateur_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lenom_UNIQUE` (`lenom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`rubriques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`rubriques` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`rubriques` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lintitule` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nad_testjuin`.`photo_has_rubriques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nad_testjuin`.`photo_has_rubriques` ;

CREATE TABLE IF NOT EXISTS `nad_testjuin`.`photo_has_rubriques` (
  `photo_id` INT UNSIGNED NOT NULL,
  `rubrique_id` INT UNSIGNED NOT NULL,
  INDEX `fk_photo_has_rubrique_rubrique1_idx` (`rubrique_id` ASC),
  INDEX `fk_photo_has_rubrique_photo1_idx` (`photo_id` ASC),
  CONSTRAINT `fk_photo_has_rubrique_photo1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `nad_testjuin`.`photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo_has_rubrique_rubrique1`
    FOREIGN KEY (`rubrique_id`)
    REFERENCES `nad_testjuin`.`rubriques` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
